addons_version: "v1.23.24" # this can be also be a version like v1.5
tenants:
  tenant1:
    addons_version: v1.3
    environments:
      dev:
        addons_version: v1.2.8
      staging:
        addons_version: v1.1
      prod:
        addons_version: v1.0
    clusters:
      cluster1:
        addons_version: v1.4
