apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: cnoe://addons
    path: "charts/gitops-bridge"
    helm:
      valuesObject:
        repoURLGit: cnoe://addons
        repoURLValues: cnoe://addons
        useSelector: false
        applicationsets:
          argocd:
            enabled: false
