apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: cnoe://addons
    path: "charts/gitops-bridge"
    helm:
      valuesObject:
        repoURLGit: cnoe://addons
        repoURLValues: cnoe://addons
        useSelector: false
        useStack: false
        addons:
          gatekeeper:
            enabled: true
          metrics_server:
            enabled: true
            values:
              args:
                - "--kubelet-insecure-tls" # this is only required in kind cluster https://gist.github.com/sanketsudake/a089e691286bf2189bfedf295222bd43
          volcano:
            enabled: true
