apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: cnoe://addons
    path: "charts/gitops-bridge"
    helm:
      valuesObject:
        repoURLGit: cnoe://addons
        repoURLValues: cnoe://addons
        useSelector: false
        applicationsets:
          argocd:
            enabled: false
          aws_load_balancer_controller:
            enabled: false
          metrics_server:
            enabled: false
          aws_ebs_csi_resources:
            enabled: false
          karpenter:
            enabled: true
          gatekeeper:
            enabled: true
            kustomize:
              patches:
                - target:
                    kind: ConfigMap
                  patch: |-
                    - op: replace
                      path: /data/foo
                      value: '{{.metadata.annotations.aws_vpc_id}}'