apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stacks
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - matrix:
          generators:
          - clusters: # for reason this is need it as second in the matrix, if not the above extracting .tenants doesn't work
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git:
              repoURL: https://gitea.cnoe.localtest.me:8443/giteaAdmin/idpbuilder-localdev-stacks-test-stacks.git
              revision: HEAD
              files:
              - path: stacks/stack-k8sv{{.metadata.annotations.kubernetes_version}}-config.yaml
              # - path: stacks/stack-k8sv{{.metadata.annotations.kubernetes_version}}-config.yaml # this doesn't work for some reason
              values:
                test_kubernetes_version: '{{.metadata.annotations.kubernetes_version}}'
      - git:
          repoURL: https://gitea.cnoe.localtest.me:8443/giteaAdmin/idpbuilder-localdev-stacks-test-stacks.git
          revision: HEAD
          files:
          - path: 'stacks/stack-k8sv{{.metadata.annotations.kubernetes_version}}-addons{{- $tenant := default dict (index .tenants .metadata.labels.tenant) -}}
          {{- $cluster := index (default dict (index $tenant "clusters")) .name -}}
          {{- $env := index (default dict (index $tenant "environments")) .metadata.labels.environment -}}
          {{- if $cluster -}}
            {{ $cluster.addons_version }}
          {{- else if $env -}}
            {{ $env.addons_version }}
          {{- else if $tenant -}}
            {{ $tenant.addons_version }}
          {{- else -}}
            {{ .addons_version }}
          {{- end -}}.yaml'
          values:
            test_addons_version: '{{.addons_version}}'
            test_kubernetes_version: '{{.metadata.annotations.kubernetes_version}}'
            test_path: 'stacks/stack-k8sv{{.metadata.annotations.kubernetes_version}}-addons{{- $tenant := default dict (index .tenants .metadata.labels.tenant) -}}
          {{- $cluster := index (default dict (index $tenant "clusters")) .name -}}
          {{- $env := index (default dict (index $tenant "environments")) .metadata.labels.environment -}}
          {{- if $cluster -}}
            {{ $cluster.addons_version }}
          {{- else if $env -}}
            {{ $env.addons_version }}
          {{- else if $tenant -}}
            {{ $tenant.addons_version }}
          {{- else -}}
            {{ .addons_version }}
          {{- end -}}.yaml'
            test_json:  |
              {{ . | mustToPrettyJson }}
# This is the same as the above, but easier to read
# {{ with index (default dict .tenants) "tenant1" }}
#   {{ with index (default dict .clusters) "cluster1" }}
#     {{ .addons_version }}
#   {{ else }}
#     {{ with index (default dict .environments) "dev" }}
#       {{ .addons_version }}
#       {{ else }}
#         {{ .addons_version }}
#     {{ end }}
#   {{ end }}
# {{ else }}
#     {{ .addons_version }}
# {{ end }}
  template:
    metadata:
      name: 'stacks-guestbook' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: cnoe://test-stacks
        path: "test/helm-guestbook"
        helm:
          values: |
            {{ . | mustToPrettyJson }}
      destination:
        name: 'in-cluster'
        namespace: guestbook
      syncPolicy:
        automated:
          selfHeal: false
          allowEmpty: true
          prune: false
        retry:
          limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.