apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  # - clusters:
  #    selector:
  #     matchLabels:
  #       argocd.argoproj.io/secret-type: cluster
  - matrix:
      generators:
      - git:
          repoURL: cnoe://addons
          revision: HEAD
          files:
          - path: stacks/stack-config.yaml
      - git:
          repoURL: cnoe://addons
          revision: HEAD
          files:
          - path: stacks/stack-k8sv1.30-addons{{ with index .tenants "tenant1" }}{{ with index .clusters "cluster1" }}{{ .stack_version }}{{ else }}{{ with index .environments "dev" }}{{ .stack_version }}{{ else }}{{ .stack_version }}{{ end }}{{ end }}{{ end }}.yaml

  template:
    metadata:
      name: '{{.path.filenameNormalized}}-guestbook' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: cnoe://addons
        path: "test"
        helm:
          values: |
            {{ . | mustToPrettyJson }}
      destination:
        name: 'in-cluster'
        namespace: guestbook
      syncPolicy:
        automated:
          selfHeal: false
          allowEmpty: true
          prune: false
        retry:
          limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.