apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-controller
  namespace: argocd
spec:
  project: default
  sources:
    - chart: aws-controllers-k8s/iam-chart
      repoURL: public.ecr.aws
      targetRevision: '1.3.7'
      helm:
        releaseName: iam-controller
        valueFiles:
          - $values/iam-controller/values.yaml
    - repoURL: cnoe://aws-controllers-k8s/manifests
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
