apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-controller-remote
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kro-run/kro/kro
      repoURL: ghcr.io
      targetRevision: '0.2.1'
      helm:
        releaseName: kro
  destination:
    name: testcluster32
    namespace: kro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
