apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-controllers-k8s-remote
  namespace: argocd
spec:
  project: default
  sources:
    - chart: aws-controllers-k8s/iam-chart
      repoURL: public.ecr.aws
      targetRevision: '1.3.16'
      helm:
        releaseName: iam-controller
        valuesObject:
          aws:
            # If specified, use the AWS region for AWS API calls
            region: "us-east-1"
    - chart: aws-controllers-k8s/eks-chart
      repoURL: public.ecr.aws
      targetRevision: '1.6.0'
      helm:
        releaseName: eks-controller
        valuesObject:
          aws:
            # If specified, use the AWS region for AWS API calls
            region: "us-east-1"
    - chart: aws-controllers-k8s/s3-chart
      repoURL: public.ecr.aws
      targetRevision: '1.0.21'
      helm:
        releaseName: s3-controller
        valuesObject:
          aws:
            # If specified, use the AWS region for AWS API calls
            region: "us-east-1"
  destination:
    name: testcluster32
    namespace: ack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
