apiVersion: v1
kind: Secret
metadata:
  name: local-secret
  namespace: crossplane-system
stringData:
  creds: |
    [default]
    aws_access_key_id = ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
