apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: podidentity.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: PodIdentity
    spec:
      name: string
      clusterName: string | default="kro"
      policyARN: string | default=""
      namespace: string | default=default
      serviceAccount: string | default=default
      region: string | default="us-east-1"
    status:
      roleArn: ${role.status.ackResourceMetadata.arn}
      podIdentityArn: ${podidentityassociation.status.ackResourceMetadata.arn}


  resources:
  - id: role
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        name: ${schema.spec.name}-role
        namespace: ${schema.metadata.namespace}
      spec:
        name: ${schema.spec.name}-role
        policies:
        - ${schema.spec.policyARN}
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "pods.eks.amazonaws.com"
                },
                "Action": [
                  "sts:AssumeRole",
                  "sts:TagSession"
                ]
              }
            ]
          }

  - id: podidentityassociation
    readyWhen:
    - ${podidentityassociation.status.conditions.exists(x, x.type == 'ACK.ResourceSynced' && x.status == "True")} #checl on ACK condition
    template:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: PodIdentityAssociation
      metadata:
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        clusterName: ${schema.spec.clusterName}
        roleARN: ${role.status.ackResourceMetadata.arn}
        serviceAccount: ${schema.spec.serviceAccount}
        namespace: ${schema.spec.namespace}

