apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: dev
    tenant: tenant1
    enable_metrics_server: "true"
    kubernetes_version: "1.29"
  annotations:
    #argocd.argoproj.io/kubernetes-version: "1.30"

    aws_vpc_id: vpc123
    aws_cluster_name: in-cluster
    # workaround for stack assignment argo can extract .name in matrix
    cluster_name: in-cluster
    aws_load_balancer_controller_service_account: sa123
    aws_load_balancer_controller_iam_role_arn: arn:aws:iam::123456789012:role/role123
    karpenter_sqs_queue_name: karpenter-interruption-queue
    karpenter_namespace: karpenter
    karpenter_service_account: karpenter
    karpenter_iam_role_arn: arn:aws:iam::123456789012:role/karpenter
    karpenter_iam_role_name: karpenter
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }