apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    enable_gatekeeper: "true"
    enable_aws_load_balancer_controller: "true"
    environment: dev
  annotations:
    platform_stack_version: "v1.30-v1.1.0"
    aws_vpc_id: vpc123
    aws_cluster_name: in-cluster
    aws_load_balancer_controller_service_account: sa123
    aws_load_balancer_controller_iam_role_arn: arn:aws:iam::123456789012:role/role123
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }