apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - name: myapp
        image: gitea.cnoe.localtest.me:8443/giteaadmin/hello-world:1.0.1
