apiVersion: kro.run/v1alpha1
kind: WebStack
metadata:
  name: test-app
spec:
  name: kro-demo-1234
  image: candonov/s3-demo-app
  s3bucket:
    enabled: true
    access: write
  ingress:
    enabled: true # this will expose unathenticated alb
  clusterName: testcluster32