apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argocd
spec:
  destination:
    namespace: clusters
    name: "in-cluster"
  source:
    repoURL: cnoe://manifests
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true