apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: ekscomposed.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: EKSComposed
    spec:
      name: string
      version: string | default="1.32"
      region: string | default="us-east-1"
      trigger: string | default="auto0"

  resources:
  - id: network
    template:
      apiVersion: kro.run/v1alpha1
      kind: NetworkingStack
      metadata:
        name: ${schema.spec.name}
      spec:
        name: ${schema.spec.name}
        region: ${schema.spec.region}
  - id: cluster
    template:
      apiVersion: kro.run/v1alpha1
      kind: EKSClusterAuto
      metadata:
        name: ${schema.spec.name}
      spec:
        name: ${schema.spec.name}
        region: ${schema.spec.region}
        version: ${schema.spec.version}
        subnetAZA: ${network.status.networkingInfo.subnetAZA}
        subnetAZB: ${network.status.networkingInfo.subnetAZB}
        trigger: ${schema.spec.trigger}


