apiVersion: v1
kind: Secret
metadata:
  name: eksdemo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "eksdemo"
  server: "https://158DF31035BA44335EE13A826934D04E.gr7.us-west-2.eks.amazonaws.com"
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eksdemo"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJV1M0TEhaakxiY1V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1UTXdOREU0TlRWYUZ3MHpOREEyTVRFd05ESXpOVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURFMmpuZXRUV2ZzU0VOT2FVdHRONTZybDMvM2xrSWxERm1VT2lYRUNCdVFWNU9scWRvL21vUU5TMnoKRHA0Q09YNVpZUU91dlN2a1NnMEhUZUxpRjdMTVp5bFB2UG9RRHMyeTY0VFIydWNTUHJCbkJsZmsrYXdkUko4VApkV2F3REZOVGZ3MVU5SVNBZXQwWUlLZmx5SU1JMkxidUdMc1dXT2pJMGtUNERVd3ZISFRWdEdRdHBXY29rRjJiCkdSejVqaE5lTy9yazE4aEhkZ3dmWVVtM3F4TTlaMGtTVDJlQlBXZlh1c1gzZ1IvVThuV0xsWHppcGhOV0RKeVMKSHdqd1lPZkt4dWRjTkY1MXR1MS9mdG1vbkt0RnBqU0pTSDRpUVRSSHF0cTFpWW9rRXdTUkwyVDhuZ3RIV012Swo2emNjNlhiS2tKSG1HV2NZSFB0QVlmYm1oNkM5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSalZyanRTZzJOTElvVFZWNkN2WHg1ZHU5d2p6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXhGMlMxZVNnegpiUDdHR3dNQWt6dndCU0Rid0oyMnE3aXVSYWJuTFBSTmRLeU1BU1ZDbXkxSEhPZEZnZkdMOC9XdXdzTGdHcUhOCmpNbEVHRjhDTjhMUE1IeGxISXdMSUhKUFN5cDBmTkdobUlRRHlqZDZGY0l6NVY0Y2pIZ3Y4UUVLNHVrdkJMcXAKUkdTUVBibHczWWI3RE1QdjJZYUlRQ3FqN0wraEt1NGJ0eExhY0k4WGpXRTBZZ2ZEZWxSTTc3U25uRk9WNm5iSgpNUHZHVG0zSi9neGtRSFgwQ05uT1RseWJ0OHNZWkQrWFFYQkUwakk4SVZXQ1RqZ1dvWXZ0R1ZKUzRCeE15ZEVUClh0VHJ5UEwrbm4xenpQVWZJTjdCbFJtZ3lxR1NWcHJwNzdTWnAzdUtYUnB6VTNHeEY0UDNXRGJUVGxyWnJaVFEKV0VUaTdTb0dYRGF3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
        }
    }
